package com.kbms_module.pojo;

import java.util.List;

/**
 * 在大分类里包装小分类
 */
public class Btype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btype.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btype.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btype.knums
     *
     * @mbggenerated
     */
    private Integer knums;
    private List<Stype> stypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btype.kquestion
     *
     * @mbggenerated
     */
    private Integer kquestion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btype.id
     *
     * @return the value of btype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btype.id
     *
     * @param id the value for btype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btype.name
     *
     * @return the value of btype.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btype.name
     *
     * @param name the value for btype.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btype.knums
     *
     * @return the value of btype.knums
     *
     * @mbggenerated
     */
    public Integer getKnums() {
        return knums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btype.knums
     *
     * @param knums the value for btype.knums
     *
     * @mbggenerated
     */
    public void setKnums(Integer knums) {
        this.knums = knums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btype.kquestion
     *
     * @return the value of btype.kquestion
     *
     * @mbggenerated
     */
    public Integer getKquestion() {
        return kquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btype.kquestion
     *
     * @param kquestion the value for btype.kquestion
     *
     * @mbggenerated
     */
    public void setKquestion(Integer kquestion) {
        this.kquestion = kquestion;
    }
    //设置小分类的得到和设置
    public List<Stype> getStypes()
    {
        return  stypes;
    }
    public void setStypes(List<Stype> smalltype)
    {
        this.stypes=smalltype;

    }
}