package com.kbms_module.pojo;



import java.util.Date;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbggenerated
     */
    private Integer id;
    private User user;
    private Integer accept;//是否被采纳
    public Integer getAccept() {
        return accept;
    }

    public void setAccept(Integer accept) {
        this.accept = accept;
    }
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.topic_id
     *
     * @mbggenerated
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbggenerated
     */
    private String content;
    //封装doc
    private Doc doc;
    private Integer replyNums;

    public Integer getReplyNums() {
        return replyNums;
    }

    public void setReplyNums(Integer replyNums) {
        this.replyNums = replyNums;
    }

    public Doc getDoc() {
        return doc;
    }

    public void setDoc(Doc doc) {
        this.doc = doc;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.c_time
     *
     * @mbggenerated
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.favers
     *
     * @mbggenerated
     */
    private Integer favers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.disfavers
     *
     * @mbggenerated
     */
    private Integer disfavers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.topic_type
     *
     * @mbggenerated
     */
    private Integer topicType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.topic_id
     *
     * @return the value of comments.topic_id
     *
     * @mbggenerated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.topic_id
     *
     * @param topicId the value for comments.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.u_id
     *
     * @return the value of comments.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.u_id
     *
     * @param uId the value for comments.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.c_time
     *
     * @return the value of comments.c_time
     *
     * @mbggenerated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.c_time
     *
     * @param cTime the value for comments.c_time
     *
     * @mbggenerated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.favers
     *
     * @return the value of comments.favers
     *
     * @mbggenerated
     */
    public Integer getFavers() {
        return favers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.favers
     *
     * @param favers the value for comments.favers
     *
     * @mbggenerated
     */
    public void setFavers(Integer favers) {
        this.favers = favers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.disfavers
     *
     * @return the value of comments.disfavers
     *
     * @mbggenerated
     */
    public Integer getDisfavers() {
        return disfavers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.disfavers
     *
     * @param disfavers the value for comments.disfavers
     *
     * @mbggenerated
     */
    public void setDisfavers(Integer disfavers) {
        this.disfavers = disfavers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.topic_type
     *
     * @return the value of comments.topic_type
     *
     * @mbggenerated
     */
    public Integer getTopicType() {
        return topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.topic_type
     *
     * @param topicType the value for comments.topic_type
     *
     * @mbggenerated
     */
    public void setTopicType(Integer topicType) {
        this.topicType = topicType;
    }
}