package com.kbms_module.pojo;

import java.util.Date;
import java.util.List;

public class Doc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.id
     *
     * @mbggenerated
     */
    private Integer id;
    private User user;
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Stype getStype() {
        return stype;
    }

    public void setStype(Stype stype) {
        this.stype = stype;
    }

    //封装小分类
    private  Stype stype;
    private String docFuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.doc_fpath
     *
     * @mbggenerated
     */
    private String docFpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.doc_fextname
     *
     * @mbggenerated
     */
    private String docFextname;

    public Btype getBtype() {
        return btype;
    }

    public void setBtype(Btype btype) {
        this.btype = btype;
    }

    //封装大分类
    private  Btype btype;

    public String getDocFuuid() {
        return docFuuid;
    }

    public void setDocFuuid(String docFuuid) {
        this.docFuuid = docFuuid;
    }

    public String getDocFpath() {
        return docFpath;
    }

    public void setDocFpath(String docFpath) {
        this.docFpath = docFpath;
    }

    public String getDocFextname() {
        return docFextname;
    }

    public void setDocFextname(String docFextname) {
        this.docFextname = docFextname;
    }

    //封装File类
    private List<File> fileList;

    public List<Tags> getTagsList() {
        return tagsList;
    }

    public void setTagsList(List<Tags> tagsList) {
        this.tagsList = tagsList;
    }

    //封装标签类
    private List<Tags> tagsList;

    public List<File> getFileList() {
        return fileList;
    }

    public void setFileList(List<File> fileList) {
        this.fileList = fileList;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.title
     *
     * @mbggenerated
     */
    private String title;

    public Integer getStypeId() {
        return StypeId;
    }

    public void setStypeId(Integer stypeId) {
        StypeId = stypeId;
    }

    private Integer StypeId;

    public Integer getBtypeId() {
        return BtypeId;
    }

    public void setBtypeId(Integer btypeId) {
        BtypeId = btypeId;
    }

    private Integer BtypeId;

    public String getPreviewurl() {
        return previewurl;
    }

    public void setPreviewurl(String previewurl) {
        this.previewurl = previewurl;
    }

    private String previewurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.author_id
     *
     * @mbggenerated
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.favers
     *
     * @mbggenerated
     */
    private Integer favers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.dislikes
     *
     * @mbggenerated
     */
    private Integer dislikes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.comments
     *
     * @mbggenerated
     */
    private Integer comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.collections
     *
     * @mbggenerated
     */
    private Integer collections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.visitnums
     *
     * @mbggenerated
     */
    private Integer visitnums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.hostnums
     *
     * @mbggenerated
     */
    private Double hostnums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.groupid
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.edittime
     *
     * @mbggenerated
     */
    private Date edittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.privcaty
     *
     * @mbggenerated
     */
    private Integer privcaty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.id
     *
     * @return the value of doc.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.id
     *
     * @param id the value for doc.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.title
     *
     * @return the value of doc.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.title
     *
     * @param title the value for doc.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.author_id
     *
     * @return the value of doc.author_id
     *
     * @mbggenerated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.author_id
     *
     * @param authorId the value for doc.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.type_id
     *
     * @return the value of doc.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.type_id
     *
     * @param typeId the value for doc.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.createTime
     *
     * @return the value of doc.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.createTime
     *
     * @param createtime the value for doc.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.favers
     *
     * @return the value of doc.favers
     *
     * @mbggenerated
     */
    public Integer getFavers() {
        return favers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.favers
     *
     * @param favers the value for doc.favers
     *
     * @mbggenerated
     */
    public void setFavers(Integer favers) {
        this.favers = favers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.dislikes
     *
     * @return the value of doc.dislikes
     *
     * @mbggenerated
     */
    public Integer getDislikes() {
        return dislikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.dislikes
     *
     * @param dislikes the value for doc.dislikes
     *
     * @mbggenerated
     */
    public void setDislikes(Integer dislikes) {
        this.dislikes = dislikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.comments
     *
     * @return the value of doc.comments
     *
     * @mbggenerated
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.comments
     *
     * @param comments the value for doc.comments
     *
     * @mbggenerated
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.collections
     *
     * @return the value of doc.collections
     *
     * @mbggenerated
     */
    public Integer getCollections() {
        return collections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.collections
     *
     * @param collections the value for doc.collections
     *
     * @mbggenerated
     */
    public void setCollections(Integer collections) {
        this.collections = collections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.visitnums
     *
     * @return the value of doc.visitnums
     *
     * @mbggenerated
     */
    public Integer getVisitnums() {
        return visitnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.visitnums
     *
     * @param visitnums the value for doc.visitnums
     *
     * @mbggenerated
     */
    public void setVisitnums(Integer visitnums) {
        this.visitnums = visitnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.hostnums
     *
     * @return the value of doc.hostnums
     *
     * @mbggenerated
     */
    public Double getHostnums() {
        return hostnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.hostnums
     *
     * @param hostnums the value for doc.hostnums
     *
     * @mbggenerated
     */
    public void setHostnums(Double hostnums) {
        this.hostnums = hostnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.groupid
     *
     * @return the value of doc.groupid
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.groupid
     *
     * @param groupid the value for doc.groupid
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.edittime
     *
     * @return the value of doc.edittime
     *
     * @mbggenerated
     */
    public Date getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.edittime
     *
     * @param edittime the value for doc.edittime
     *
     * @mbggenerated
     */
    public void setEdittime(Date edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.privcaty
     *
     * @return the value of doc.privcaty
     *
     * @mbggenerated
     */
    public Integer getPrivcaty() {
        return privcaty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.privcaty
     *
     * @param privcaty the value for doc.privcaty
     *
     * @mbggenerated
     */
    public void setPrivcaty(Integer privcaty) {
        this.privcaty = privcaty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.summary
     *
     * @return the value of doc.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.summary
     *
     * @param summary the value for doc.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.tags
     *
     * @return the value of doc.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.tags
     *
     * @param tags the value for doc.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc.content
     *
     * @return the value of doc.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc.content
     *
     * @param content the value for doc.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}