package com.kbms_module.pojo;

import java.util.Date;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.comments
     *
     * @mbggenerated
     */
    private Integer comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.vistists
     *
     * @mbggenerated
     */
    private String vistists;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.useid
     *
     * @mbggenerated
     */
    private Integer useid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.posttime
     *
     * @mbggenerated
     */
    private Date posttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.hotnum
     *
     * @mbggenerated
     */
    private Double hotnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.P_kindid
     *
     * @mbggenerated
     */
    private Integer pKindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.followuser_id
     *
     * @mbggenerated
     */
    private Integer followuserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.collection
     *
     * @mbggenerated
     */
    private Integer collection;
    //封装大分类
    private  Btype btype;
    //封装小分类
    private  Stype stype;
    //封装用户
    private User user;
    private Integer bid;
    public Integer getBid() {
        return bid;
    }

    public void setBid(Integer bid) {
        this.bid = bid;
    }



    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Btype getBtype() {
        return btype;
    }

    public void setBtype(Btype btype) {
        this.btype = btype;
    }

    public Stype getStype() {
        return stype;
    }

    public void setStype(Stype stype) {
        this.stype = stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbggenerated
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.comments
     *
     * @return the value of question.comments
     *
     * @mbggenerated
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.comments
     *
     * @param comments the value for question.comments
     *
     * @mbggenerated
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.vistists
     *
     * @return the value of question.vistists
     *
     * @mbggenerated
     */
    public String getVistists() {
        return vistists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.vistists
     *
     * @param vistists the value for question.vistists
     *
     * @mbggenerated
     */
    public void setVistists(String vistists) {
        this.vistists = vistists == null ? null : vistists.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.useid
     *
     * @return the value of question.useid
     *
     * @mbggenerated
     */
    public Integer getUseid() {
        return useid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.useid
     *
     * @param useid the value for question.useid
     *
     * @mbggenerated
     */
    public void setUseid(Integer useid) {
        this.useid = useid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.posttime
     *
     * @return the value of question.posttime
     *
     * @mbggenerated
     */
    public Date getPosttime() {
        return posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.posttime
     *
     * @param posttime the value for question.posttime
     *
     * @mbggenerated
     */
    public void setPosttime(Date posttime) {
        this.posttime = posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.hotnum
     *
     * @return the value of question.hotnum
     *
     * @mbggenerated
     */
    public Double getHotnum() {
        return hotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.hotnum
     *
     * @param hotnum the value for question.hotnum
     *
     * @mbggenerated
     */
    public void setHotnum(Double hotnum) {
        this.hotnum = hotnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.P_kindid
     *
     * @return the value of question.P_kindid
     *
     * @mbggenerated
     */
    public Integer getpKindid() {
        return pKindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.P_kindid
     *
     * @param pKindid the value for question.P_kindid
     *
     * @mbggenerated
     */
    public void setpKindid(Integer pKindid) {
        this.pKindid = pKindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.status
     *
     * @return the value of question.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.status
     *
     * @param status the value for question.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.followuser_id
     *
     * @return the value of question.followuser_id
     *
     * @mbggenerated
     */
    public Integer getFollowuserId() {
        return followuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.followuser_id
     *
     * @param followuserId the value for question.followuser_id
     *
     * @mbggenerated
     */
    public void setFollowuserId(Integer followuserId) {
        this.followuserId = followuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.collection
     *
     * @return the value of question.collection
     *
     * @mbggenerated
     */
    public Integer getCollection() {
        return collection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.collection
     *
     * @param collection the value for question.collection
     *
     * @mbggenerated
     */
    public void setCollection(Integer collection) {
        this.collection = collection;
    }
}