package com.kbms_module.pojo;

public class Stype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stype.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stype.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stype.k_nums
     *
     * @mbggenerated
     */
    private Integer kNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stype.Pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stype.id
     *
     * @return the value of stype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stype.id
     *
     * @param id the value for stype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stype.name
     *
     * @return the value of stype.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stype.name
     *
     * @param name the value for stype.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stype.k_nums
     *
     * @return the value of stype.k_nums
     *
     * @mbggenerated
     */
    public Integer getkNums() {
        return kNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stype.k_nums
     *
     * @param kNums the value for stype.k_nums
     *
     * @mbggenerated
     */
    public void setkNums(Integer kNums) {
        this.kNums = kNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stype.Pid
     *
     * @return the value of stype.Pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stype.Pid
     *
     * @param pid the value for stype.Pid
     *
             * @mbggenerated
     */
public void setPid(Integer pid) {
        this.pid = pid;
        }
        }