package com.kbms_module.pojo;

public class Tags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.tag_hots
     *
     * @mbggenerated
     */
    private Integer tagHots;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.posts
     *
     * @mbggenerated
     */
    private Integer posts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.tag_hots
     *
     * @return the value of tags.tag_hots
     *
     * @mbggenerated
     */
    public Integer getTagHots() {
        return tagHots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.tag_hots
     *
     * @param tagHots the value for tags.tag_hots
     *
     * @mbggenerated
     */
    public void setTagHots(Integer tagHots) {
        this.tagHots = tagHots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.posts
     *
     * @return the value of tags.posts
     *
     * @mbggenerated
     */
    public Integer getPosts() {
        return posts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.posts
     *
     * @param posts the value for tags.posts
     *
     * @mbggenerated
     */
    public void setPosts(Integer posts) {
        this.posts = posts;
    }
}