package com.generator.dao;

import com.generator.pojo.Associationdoc;

public interface AssociationdocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table associationdoc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table associationdoc
     *
     * @mbggenerated
     */
    int insert(Associationdoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table associationdoc
     *
     * @mbggenerated
     */
    int insertSelective(Associationdoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table associationdoc
     *
     * @mbggenerated
     */
    Associationdoc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table associationdoc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Associationdoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table associationdoc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Associationdoc record);
}