package com.generator.dao;

import com.generator.pojo.Btype;

public interface BtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btype
     *
     * @mbggenerated
     */
    int insert(Btype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btype
     *
     * @mbggenerated
     */
    int insertSelective(Btype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btype
     *
     * @mbggenerated
     */
    Btype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Btype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Btype record);
}