package com.generator.dao;

import com.generator.pojo.DocTag;

public interface DocTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_tag
     *
     * @mbggenerated
     */
    int insert(DocTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_tag
     *
     * @mbggenerated
     */
    int insertSelective(DocTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_tag
     *
     * @mbggenerated
     */
    DocTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocTag record);
}