package com.generator.dao;

import com.generator.pojo.Filedoc;

public interface FiledocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated
     */
    int insert(Filedoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated
     */
    int insertSelective(Filedoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated
     */
    Filedoc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Filedoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Filedoc record);
}