package com.generator.dao;

import com.generator.pojo.KGroup;

public interface KGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k_group
     *
     * @mbggenerated
     */
    int insert(KGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table k_group
     *
     * @mbggenerated
     */
    int insertSelective(KGroup record);
}