package com.generator.dao;

import com.generator.pojo.Replys;

public interface ReplysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replys
     *
     * @mbggenerated
     */
    int insert(Replys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replys
     *
     * @mbggenerated
     */
    int insertSelective(Replys record);
}