package com.generator.dao;

import com.generator.pojo.Stype;

public interface StypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stype
     *
     * @mbggenerated
     */
    int insert(Stype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stype
     *
     * @mbggenerated
     */
    int insertSelective(Stype record);
}