package com.generator.dao;

import com.generator.pojo.Zan;

public interface ZanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated
     */
    int insert(Zan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbggenerated
     */
    int insertSelective(Zan record);
}