package com.generator.pojo;

public class Associationdoc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associationdoc.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associationdoc.newid
     *
     * @mbggenerated
     */
    private Integer newid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column associationdoc.oldid
     *
     * @mbggenerated
     */
    private Integer oldid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associationdoc.id
     *
     * @return the value of associationdoc.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associationdoc.id
     *
     * @param id the value for associationdoc.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associationdoc.newid
     *
     * @return the value of associationdoc.newid
     *
     * @mbggenerated
     */
    public Integer getNewid() {
        return newid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associationdoc.newid
     *
     * @param newid the value for associationdoc.newid
     *
     * @mbggenerated
     */
    public void setNewid(Integer newid) {
        this.newid = newid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column associationdoc.oldid
     *
     * @return the value of associationdoc.oldid
     *
     * @mbggenerated
     */
    public Integer getOldid() {
        return oldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column associationdoc.oldid
     *
     * @param oldid the value for associationdoc.oldid
     *
     * @mbggenerated
     */
    public void setOldid(Integer oldid) {
        this.oldid = oldid;
    }
}