package com.generator.pojo;

public class DocTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_tag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_tag.docid
     *
     * @mbggenerated
     */
    private Integer docid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_tag.tagid
     *
     * @mbggenerated
     */
    private Integer tagid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_tag.id
     *
     * @return the value of doc_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_tag.id
     *
     * @param id the value for doc_tag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_tag.docid
     *
     * @return the value of doc_tag.docid
     *
     * @mbggenerated
     */
    public Integer getDocid() {
        return docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_tag.docid
     *
     * @param docid the value for doc_tag.docid
     *
     * @mbggenerated
     */
    public void setDocid(Integer docid) {
        this.docid = docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_tag.tagid
     *
     * @return the value of doc_tag.tagid
     *
     * @mbggenerated
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_tag.tagid
     *
     * @param tagid the value for doc_tag.tagid
     *
     * @mbggenerated
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }
}