package com.generator.pojo;

public class Filedoc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.fileid
     *
     * @mbggenerated
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filedoc.docid
     *
     * @mbggenerated
     */
    private Integer docid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.id
     *
     * @return the value of filedoc.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.id
     *
     * @param id the value for filedoc.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.fileid
     *
     * @return the value of filedoc.fileid
     *
     * @mbggenerated
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.fileid
     *
     * @param fileid the value for filedoc.fileid
     *
     * @mbggenerated
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filedoc.docid
     *
     * @return the value of filedoc.docid
     *
     * @mbggenerated
     */
    public Integer getDocid() {
        return docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filedoc.docid
     *
     * @param docid the value for filedoc.docid
     *
     * @mbggenerated
     */
    public void setDocid(Integer docid) {
        this.docid = docid;
    }
}