package com.generator.pojo;

import java.util.Date;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.dir
     *
     * @mbggenerated
     */
    private String dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.len
     *
     * @mbggenerated
     */
    private Integer len;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.cusername
     *
     * @mbggenerated
     */
    private String cusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.cuserid
     *
     * @mbggenerated
     */
    private Integer cuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.exname
     *
     * @mbggenerated
     */
    private String exname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.filetempname
     *
     * @mbggenerated
     */
    private String filetempname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.downloadnums
     *
     * @mbggenerated
     */
    private Integer downloadnums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.serverid
     *
     * @mbggenerated
     */
    private Integer serverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.filepath
     *
     * @mbggenerated
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.filestate
     *
     * @mbggenerated
     */
    private Integer filestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.fileuuid
     *
     * @mbggenerated
     */
    private String fileuuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.title
     *
     * @return the value of file.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.title
     *
     * @param title the value for file.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.createtime
     *
     * @return the value of file.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.createtime
     *
     * @param createtime the value for file.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.dir
     *
     * @return the value of file.dir
     *
     * @mbggenerated
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.dir
     *
     * @param dir the value for file.dir
     *
     * @mbggenerated
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.len
     *
     * @return the value of file.len
     *
     * @mbggenerated
     */
    public Integer getLen() {
        return len;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.len
     *
     * @param len the value for file.len
     *
     * @mbggenerated
     */
    public void setLen(Integer len) {
        this.len = len;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.cusername
     *
     * @return the value of file.cusername
     *
     * @mbggenerated
     */
    public String getCusername() {
        return cusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.cusername
     *
     * @param cusername the value for file.cusername
     *
     * @mbggenerated
     */
    public void setCusername(String cusername) {
        this.cusername = cusername == null ? null : cusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.cuserid
     *
     * @return the value of file.cuserid
     *
     * @mbggenerated
     */
    public Integer getCuserid() {
        return cuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.cuserid
     *
     * @param cuserid the value for file.cuserid
     *
     * @mbggenerated
     */
    public void setCuserid(Integer cuserid) {
        this.cuserid = cuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.exname
     *
     * @return the value of file.exname
     *
     * @mbggenerated
     */
    public String getExname() {
        return exname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.exname
     *
     * @param exname the value for file.exname
     *
     * @mbggenerated
     */
    public void setExname(String exname) {
        this.exname = exname == null ? null : exname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.filetempname
     *
     * @return the value of file.filetempname
     *
     * @mbggenerated
     */
    public String getFiletempname() {
        return filetempname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.filetempname
     *
     * @param filetempname the value for file.filetempname
     *
     * @mbggenerated
     */
    public void setFiletempname(String filetempname) {
        this.filetempname = filetempname == null ? null : filetempname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.downloadnums
     *
     * @return the value of file.downloadnums
     *
     * @mbggenerated
     */
    public Integer getDownloadnums() {
        return downloadnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.downloadnums
     *
     * @param downloadnums the value for file.downloadnums
     *
     * @mbggenerated
     */
    public void setDownloadnums(Integer downloadnums) {
        this.downloadnums = downloadnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.serverid
     *
     * @return the value of file.serverid
     *
     * @mbggenerated
     */
    public Integer getServerid() {
        return serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.serverid
     *
     * @param serverid the value for file.serverid
     *
     * @mbggenerated
     */
    public void setServerid(Integer serverid) {
        this.serverid = serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.filepath
     *
     * @return the value of file.filepath
     *
     * @mbggenerated
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.filepath
     *
     * @param filepath the value for file.filepath
     *
     * @mbggenerated
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.filestate
     *
     * @return the value of file.filestate
     *
     * @mbggenerated
     */
    public Integer getFilestate() {
        return filestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.filestate
     *
     * @param filestate the value for file.filestate
     *
     * @mbggenerated
     */
    public void setFilestate(Integer filestate) {
        this.filestate = filestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.fileuuid
     *
     * @return the value of file.fileuuid
     *
     * @mbggenerated
     */
    public String getFileuuid() {
        return fileuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.fileuuid
     *
     * @param fileuuid the value for file.fileuuid
     *
     * @mbggenerated
     */
    public void setFileuuid(String fileuuid) {
        this.fileuuid = fileuuid == null ? null : fileuuid.trim();
    }
}