package com.generator.pojo;

import java.util.Date;

public class Replys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.reply_id
     *
     * @mbggenerated
     */
    private Integer replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.replay_type
     *
     * @mbggenerated
     */
    private String replayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.f_userid
     *
     * @mbggenerated
     */
    private Integer fUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.to_userid
     *
     * @mbggenerated
     */
    private Integer toUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replys.c_time
     *
     * @mbggenerated
     */
    private Date cTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.id
     *
     * @return the value of replys.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.id
     *
     * @param id the value for replys.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.comment_id
     *
     * @return the value of replys.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.comment_id
     *
     * @param commentId the value for replys.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.reply_id
     *
     * @return the value of replys.reply_id
     *
     * @mbggenerated
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.reply_id
     *
     * @param replyId the value for replys.reply_id
     *
     * @mbggenerated
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.replay_type
     *
     * @return the value of replys.replay_type
     *
     * @mbggenerated
     */
    public String getReplayType() {
        return replayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.replay_type
     *
     * @param replayType the value for replys.replay_type
     *
     * @mbggenerated
     */
    public void setReplayType(String replayType) {
        this.replayType = replayType == null ? null : replayType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.content
     *
     * @return the value of replys.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.content
     *
     * @param content the value for replys.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.f_userid
     *
     * @return the value of replys.f_userid
     *
     * @mbggenerated
     */
    public Integer getfUserid() {
        return fUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.f_userid
     *
     * @param fUserid the value for replys.f_userid
     *
     * @mbggenerated
     */
    public void setfUserid(Integer fUserid) {
        this.fUserid = fUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.to_userid
     *
     * @return the value of replys.to_userid
     *
     * @mbggenerated
     */
    public Integer getToUserid() {
        return toUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.to_userid
     *
     * @param toUserid the value for replys.to_userid
     *
     * @mbggenerated
     */
    public void setToUserid(Integer toUserid) {
        this.toUserid = toUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replys.c_time
     *
     * @return the value of replys.c_time
     *
     * @mbggenerated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replys.c_time
     *
     * @param cTime the value for replys.c_time
     *
     * @mbggenerated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }
}