package com.generator.pojo;

public class Zan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.stastus
     *
     * @mbggenerated
     */
    private String stastus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.id
     *
     * @return the value of zan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.id
     *
     * @param id the value for zan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.type_id
     *
     * @return the value of zan.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.type_id
     *
     * @param typeId the value for zan.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.type
     *
     * @return the value of zan.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.type
     *
     * @param type the value for zan.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.user_id
     *
     * @return the value of zan.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.user_id
     *
     * @param userId the value for zan.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.stastus
     *
     * @return the value of zan.stastus
     *
     * @mbggenerated
     */
    public String getStastus() {
        return stastus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.stastus
     *
     * @param stastus the value for zan.stastus
     *
     * @mbggenerated
     */
    public void setStastus(String stastus) {
        this.stastus = stastus == null ? null : stastus.trim();
    }
}