package com.kbms_module.dao;


import com.kbms_module.pojo.Btype;
import com.kbms_module.pojo.Stype;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btype
     *
     * @mbggenerated
     */
    int insert(Btype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btype
     *
     * @mbggenerated
     */
    int insertSelective(Btype record);
    /**
     * 查找所有的类别
     */
    List<Btype> selectAllbyte();
    /**
     * 根据大类别的id查找所有的小id,需要参数绑定
     */
    List<Stype> selectAllbyBtype(@Param("id") int id);
    /**
     *
     * 得到type
     */
    Btype selectTypebyId(int id);

    void updatednums(@Param("bid") Integer integer, @Param("bdocnums") Integer bdocnums);
}