package com.kbms_module.dao;


import com.kbms_module.pojo.Comments;
import com.kbms_module.pojo.Replys;
import org.apache.ibatis.annotations.Param;

import java.sql.Timestamp;
import java.util.List;

public interface CommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated
     */
    int insert(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated
     */
    int insertSelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated
     */
    Comments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Comments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Comments record);

    List<Comments> getLastestComments(Integer i);

    /**
     * 得到评论列表根据文档id或者用户id
     * @param did
     * @param uid
     * @return
     */
    List<Comments> getCommentsById(@Param("did") Integer did, @Param("uid") Integer uid);

    /**
     * 得到回复列表
     * @param id
     * @param cid
     * @return
     */
    List<Replys> getReplyById(@Param("id") Integer id, @Param("cid") Integer cid);

    int addComment(@Param("did") Integer did, @Param("uid") Integer uid, @Param("content") String content, @Param("timestamp") Timestamp timestamp);

    /**
     * 的到
     * @param qid
     * @return
     */
    Comments getSureAnswerForQuestion(Integer qid);

    List<Comments> getUsureAnswerForQuestion(Integer qid);
}