package com.kbms_module.dao;

import com.generator.pojo.Doc;

public interface DocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int insert(Doc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int insertSelective(Doc record);
}