package com.kbms_module.dao;

import com.kbms_module.pojo.Filedoc;
import org.apache.ibatis.annotations.Param;

public interface FiledocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated
     */
    int insert(Filedoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filedoc
     *
     * @mbggenerated
     */
    int insertSelective(Filedoc record);

    /**
     * 添加附件
     * @param id
     * @param id1
     */


    void createFileForDoc(Filedoc filedoc);
}