package com.kbms_module.dao;


import com.kbms_module.pojo.Doc;
import com.kbms_module.pojo.Group;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    int insertSelective(Group record);

    List<Group> getlastestgroup(Integer i);

    List<Group> getAllGroup();

    Group getUserForGroup(Integer gid);

    List<Doc> getDocsbyGid(Integer gid);

    void createGroup(Group group);

    void createUserGroup(@Param("userId") Integer userId, @Param("id") Integer id);
}