package com.kbms_module.dao;

import com.kbms_module.pojo.Stype;
import org.apache.ibatis.annotations.Param;

public interface StypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stype
     *
     * @mbggenerated
     */
    int insert(Stype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stype
     *
     * @mbggenerated
     */
    int insertSelective(Stype record);

    /**
     *
     * @return根据小分类的id查找出所有信息
     */
     Stype selectById(int id);

    void uodatenums(@Param("sid") Integer integer, @Param("sdocnums") Integer sdocnums);
}