package com.kbms_module.dao;

import com.kbms_module.pojo.Tags;
import org.apache.ibatis.annotations.Param;

public interface TagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbggenerated
     */
    int insert(Tags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbggenerated
     */
    int insertSelective(Tags record);

    /**
     *
     * @param t
     * @return
     */
     com.kbms_module.pojo.Tags selectTagbyname(String t);

    void updatePost(@Param("tid") int tid, @Param("tagnum") int tagnum);



    void createTag(Tags tagg);
}